### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by chuhades** [antoor/antSword#2]
➜ antSword (master) ✗ npm run build

> antsword@1.0.0 build /home/chu/Pentest/antSword
> webpack --progress --color --watch

/home/chu/Pentest/antSword/webpack.config.js:3
const webpack = require('webpack');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm ERR! antsword@1.0.0 build: `webpack --progress --color --watch`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the antsword@1.0.0 build script.
npm ERR! This is most likely a problem with the antsword package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --color --watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls antsword
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! cwd /home/chu/Pentest/antSword
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/chu/Pentest/antSword/npm-debug.log
npm ERR! not ok code 0

**Comment by antoor** [comment]
你的nodejs版本是多少？貌似不支持新语法。。（本人测试4.x以上的

**Comment by antoor** [comment]
你的nodejs版本是多少？貌似不支持新语法。。（本人测试4.x以上的
