### ISSUE TITLE
process.env.AS_WORKDIR 为undefined的错误

### ISSUE THREAD

**Issue by potapo** [antoor/antSword#74]
+ 电脑环境 mac serria 
+ elecrton v1.4.3
+ nodejs   6.8.0

中国蚁剑是2.0开发版

在执行npm start，会报错
```
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at new Conf (/Volumes/Transcend/Downloads/antSword-2.0-beta/modules/config.js:24:26)
    at Object.<anonymous> (/Volumes/Transcend/Downloads/antSword-2.0-beta/modules/config.js:91:18)
```

**Comment by Medicean** [comment]
2.0 代码需要使用定制的加载器加载源代码，源代码不能直接运行。

感谢支持。

**Comment by potapo** [comment]
谢谢啦，哪能告诉我是什么加载器吗？或者有什么相关帮助文档吗？我回去看看。谢谢啦

**Comment by Medicean** [comment]
加载器和2.0目前邀请了一小部分人内测使用，暂不对外提供。内测结束后会发布。

**Comment by potapo** [comment]
那好吧，谢谢解答\(^o^)/
