### ISSUE TITLE
2.0 beta 无法正常启动

### ISSUE THREAD

**Issue by greenhand2learn** [antoor/antSword#90]
缺少 `electron` 
```
sh: 1: electron: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! antsword@2.0.0 start: `electron app.js`
npm ERR! spawn ENOENT
```
手动安装 `electron` 切换多个版本都无法正常启动，报错如下
```
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at new Conf (ant2.0-beta/modules/config.js:24:26)
    at Object.<anonymous> (ant2.0-beta/modules/config.js:90:18)
    at Object.<anonymous> (ant2.0-beta/modules/config.js:92:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
系统 `Deepin Linux`

**Comment by Medicean** [comment]
参考： https://github.com/antoor/antSword/blob/doc/zh-hans/getting_started/get_antsword.md

**Comment by greenhand2learn** [comment]
@Medicean 加速器链接。。。。呢？

**Comment by Medicean** [comment]
暂未对外发布，等邀请内测结束后会发布
